version: '3.5'
services:

  postgres:
    container_name: chemondis_psql
    image: postgres:latest
    env_file: ../src/.env
    ports:
      - 5432:5432
    volumes:
      - ./db_volume:/var/lib/postgresql/data

  web:
    container_name: chemondis_web
    build:
      context: ../.
      dockerfile: ./docker/web/Dockerfile
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    entrypoint: /src/docker/web-entrypoint.sh
    env_file: ../src/.env
    volumes:
      - ../src/static:/src/static/
      - ../src/templates:/src/templates/
    expose:
      - 8000
    depends_on:
      - postgres

  asgiserver:
    build:
      context: ../.
      dockerfile: ./docker/asgi/Dockerfile
    restart: always
    container_name: chemondis_asgi
    command: daphne app.asgi:application --bind 0.0.0.0 --port 8010
    depends_on:
      - redis
    expose:
      - 8010

  redis:
    container_name: chemondis_redis
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

  nginx:
    container_name: chemondis_nginx
    build:
      context: ../.
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    volumes:
      - ../src/static:/src/static/
      - ../src/templates:/src/templates/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  db_volume:
